mutation ConnectVirtualPresence($input: ConnectVirtualPresenceInput) {
  connectVirtualPresence(input: $input) {
    ...VirtualPresenceFields
  }
}

mutation DisconnectVirtualPresence($id: String!) {
  disconnectVirtualPresence(id: $id) {
    ...VirtualPresenceFields
  }
}

mutation RescanVirtualPresence($id: String!, $options: ScanOptionsInput) {
  rescanVirtualPresence(id: $id, options: $options) {
    ...VirtualPresenceFields
  }
}

mutation InitiateAction($input: InitiateActionInput!) {
  initiateAction(input: $input) {
    ...ActionFields
  }
}

mutation ConfirmActionOutcome($id: ID!) {
  confirmActionOutcome(id: $id) {
    ...ActionFields
  }
}
