/**
 * Copyright © 2026 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { DataHolderSubscriber } from '../../../../public/typings/subscription'
import { DataHolderEntity } from './dataHolderEntity'

/**
 * Input for `DataHolderService.list` method.
 *
 * @interface ListDataHoldersInput
 * @property {string} virtualPresenceId The virtual presence to list data holders for.
 * @property {number} limit Number of records to return.
 * @property {string} nextToken A token generated by a previous call to `DataHolderService.list`.
 *  This allows for pagination.
 */
export interface ListDataHoldersInput {
  virtualPresenceId: string
  limit?: number
  nextToken?: string
}

/**
 * Output for `DataHolderService.list` method.
 *
 * @interface ListDataHoldersOutput
 * @property {DataHolderEntity[]} dataHolders The list of data holders retrieved in this query.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
export interface ListDataHoldersOutput {
  dataHolders: DataHolderEntity[]
  nextToken?: string
}

/**
 * Input for `DataHolderService.subscribe` method.
 *
 * @interface SubscribeToDataHolderInput
 * @property {string} subscriptionId A unique identifier for this subscription.
 * @property {string} owner The identifier of the owner to subscribe for.
 * @property {DataHolderSubscriber} subscriber The subscriber to receive events.
 */
export interface SubscribeToDataHoldersInput {
  subscriptionId: string
  owner: string
  subscriber: DataHolderSubscriber
}

/**
 * Core entity representation of a data holder service used in business logic.
 * Used to perform CRUD operations for data holders.
 *
 * @interface DataHolderService
 */
export interface DataHolderService {
  /**
   * Retrieve a single data holder by ID.
   *
   * @param {string} id The unique identifier of the data holder.
   * @returns {DataHolderEntity | undefined} The data holder, or undefined if not found.
   */
  get(id: string): Promise<DataHolderEntity | undefined>

  /**
   * Retrieve a list of data holders for a virtual presence.
   *
   * @param {ListDataHoldersInput} input Parameters used to list data holders.
   * @returns {ListDataHoldersOutput} A list of data holders matching the search criteria.
   *  Can be empty if no data holders found.
   */
  list(input: ListDataHoldersInput): Promise<ListDataHoldersOutput>

  /**
   * Subscribe to data holder state events.
   *
   * @param {SubscribeToDataHoldersInput} input Parameters used to subscribe to data
   *  holder state events.
   */
  subscribe(input: SubscribeToDataHoldersInput): Promise<void>

  /**
   * Unsubscribe from data holder state events.
   *
   * @param {string} subscriptionId The unique identifier of the subscription to unsubscribe from.
   */
  unsubscribe(subscriptionId: string): void
}
