/**
 * Copyright © 2026 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { VirtualPresenceSubscriber } from '../../../../public/typings/subscription'
import { RelationshipProviderEntity } from '../inputs/relationshipProviderEntity'
import { ScanOptionsEntity } from '../inputs/scanOptionsEntity'
import { VirtualPresenceEntity } from './virtualPresenceEntity'

/**
 * Auth code input for connecting a virtual presence.
 *
 * @interface AuthCodeInput
 * @property {string} authCode The auth code value.
 * @property {string} redirectUri The optional redirect URI value.
 */
export interface AuthCodeInput {
  authCode: string
  redirectUri?: string
}

/**
 * Refresh token credential input for connecting a virtual presence.
 *
 * @interface RefreshTokenInput
 * @property {string} refreshToken The refresh token value.
 * @property {string} providerIdentity The identity associated with the provider.
 * @property {string[]} scopes Optional OAuth scopes associated with the token.
 * @property {number} expiresInEpochMs Optional expiration time in milliseconds since epoch.
 */
export interface RefreshTokenInput {
  refreshToken: string
  providerIdentity: string
  scopes?: string[]
  expiresInEpochMs?: number
}

/**
 * Input for `VirtualPresenceService.connect` method.
 *
 * @interface ConnectVirtualPresenceInput
 * @property {AuthCodeInput} authCode An authorization code obtained from the OAuth flow.
 * @property {RefreshTokenInput} refreshToken A pre-obtained refresh token credential.
 * @property {RelationshipProviderEntity} relationshipProvider The relationship provider
 *  to associate with the connection.
 */
export interface ConnectVirtualPresenceInput {
  authCode?: AuthCodeInput
  refreshToken?: RefreshTokenInput
  relationshipProvider?: RelationshipProviderEntity
}

/**
 * Input for `VirtualPresenceService.list` method.
 *
 * @interface ListVirtualPresencesInput
 * @property {number} limit Number of records to return.
 * @property {string} nextToken A token generated by a previous call to `VirtualPresenceService.list`.
 *  This allows for pagination.
 */
export interface ListVirtualPresencesInput {
  limit?: number
  nextToken?: string
}

/**
 * Input for `VirtualPresenceService.rescan` method.
 *
 * @interface RescanVirtualPresenceInput
 * @property {string} id The unique identifier of the virtual presence to rescan.
 * @property {ScanOptionsEntity} options Optional scan options to control the rescan behavior.
 */
export interface RescanVirtualPresenceInput {
  id: string
  options?: ScanOptionsEntity
}

/**
 * Output for `VirtualPresenceService.list` method.
 *
 * @interface ListVirtualPresencesOutput
 * @property {VirtualPresenceEntity[]} virtualPresences The list of virtual presences retrieved in this query.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
export interface ListVirtualPresencesOutput {
  virtualPresences: VirtualPresenceEntity[]
  nextToken?: string
}

/**
 * Input for `VirtualPresenceService.subscribe` method.
 *
 * @interface SubscribeToVirtualPresenceInput
 * @property {string} subscriptionId A unique identifier for this subscription.
 * @property {string} owner The identifier of the owner to subscribe for.
 * @property {VirtualPresenceSubscriber} subscriber The subscriber to receive events.
 */
export interface SubscribeToVirtualPresenceInput {
  subscriptionId: string
  owner: string
  subscriber: VirtualPresenceSubscriber
}

/**
 * Core entity representation of a virtual presence service used in business logic.
 * Used to perform CRUD operations for virtual presences.
 *
 * @interface VirtualPresenceService
 */
export interface VirtualPresenceService {
  /**
   * Connect a virtual presence using an auth code or refresh token.
   *
   * @param {ConnectVirtualPresenceInput} input Parameters used to connect a virtual presence.
   * @returns {VirtualPresenceEntity} The connected virtual presence.
   */
  connect(input: ConnectVirtualPresenceInput): Promise<VirtualPresenceEntity>

  /**
   * Retrieve a list of virtual presences.
   *
   * @param {ListVirtualPresencesInput} input Parameters used to list virtual presences.
   * @returns {ListVirtualPresencesOutput} A list of all virtual presences matching the search criteria.
   *  Can be empty if no virtual presences found.
   */
  list(input: ListVirtualPresencesInput): Promise<ListVirtualPresencesOutput>

  /**
   * Disconnect a virtual presence by ID.
   *
   * @param {string} id The unique identifier of the virtual presence to disconnect.
   * @returns {VirtualPresenceEntity} The disconnected virtual presence.
   */
  disconnect(id: string): Promise<VirtualPresenceEntity>

  /**
   * Rescan a virtual presence by ID.
   *
   * @param {RescanVirtualPresenceInput} input Parameters used to rescan a virtual presence.
   * @returns {VirtualPresenceEntity} The rescanned virtual presence.
   */
  rescan(input: RescanVirtualPresenceInput): Promise<VirtualPresenceEntity>

  /**
   * Subscribe to virtual presence state events.
   *
   * @param {SubscribeToVirtualPresenceUpdatesInput} input Parameters used to subscribe to virtual
   *  presence state events.
   */
  subscribe(input: SubscribeToVirtualPresenceInput): Promise<void>

  /**
   * Unsubscribe from virtual presence state events.
   *
   * @param {string} subscriptionId The unique identifier of the subscription to unsubscribe from.
   */
  unsubscribe(subscriptionId: string): void
}
