/**
 * Copyright © 2026 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { ActionSubscriber } from '../../../../public/typings/subscription'
import {
  ActionEntity,
  ActionFulfilmentMethodEntity,
  ActionIntentEntity,
  AvailableActionEntity,
} from './actionEntity'

/**
 * Input for `ActionService.initiate` method.
 *
 * @interface InitiateActionInput
 * @property {string} dataHolderId The data holder relationship to scope the action to.
 * @property {ActionIntentEntity} intent The intent of the action to initiate.
 * @property {ActionFulfilmentMethodEntity} fulfilmentMethod The fulfilment method the
 *  client was offered for this intent.
 */
export interface InitiateActionInput {
  dataHolderId: string
  intent: ActionIntentEntity
  fulfilmentMethod: ActionFulfilmentMethodEntity
}

/**
 * Input for `ActionService.listAvailable` method.
 *
 * @interface ListAvailableActionsInput
 * @property {string} dataHolderId The data holder relationship to list available actions for.
 */
export interface ListAvailableActionsInput {
  dataHolderId: string
}

/**
 * Output for `ActionService.listAvailable` method.
 *
 * @interface ListAvailableActionsOutput
 * @property {AvailableActionEntity[]} availableActions The list of available actions
 *  retrieved in this query.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
export interface ListAvailableActionsOutput {
  availableActions: AvailableActionEntity[]
  nextToken?: string
}

/**
 * Input for `ActionService.subscribe` method.
 *
 * @interface SubscribeToActionsInput
 * @property {string} subscriptionId A unique identifier for this subscription.
 * @property {string} owner The identifier of the owner to subscribe for.
 * @property {ActionSubscriber} subscriber The subscriber to receive events.
 */
export interface SubscribeToActionsInput {
  subscriptionId: string
  owner: string
  subscriber: ActionSubscriber
}

/**
 * Core entity representation of an action service used in business logic.
 * Used to initiate, confirm, and list actions against data holder relationships.
 *
 * @interface ActionService
 */
export interface ActionService {
  /**
   * Initiate an action against a data holder relationship.
   *
   * @param {InitiateActionInput} input Parameters used to initiate the action.
   * @returns {ActionEntity} The initiated action.
   */
  initiate(input: InitiateActionInput): Promise<ActionEntity>

  /**
   * Confirm that an assisted or delegated action was completed, transitioning it
   * from `CompletedUnverified` to `CompletedVerified`.
   *
   * @param {string} id The unique identifier of the action to confirm.
   * @returns {ActionEntity} The confirmed action.
   */
  confirmOutcome(id: string): Promise<ActionEntity>

  /**
   * Retrieve the list of actions currently available for a data holder relationship.
   *
   * @param {ListAvailableActionsInput} input Parameters used to list available actions.
   * @returns {ListAvailableActionsOutput} A list of available actions. Can be empty if
   *  no actions are available.
   */
  listAvailable(
    input: ListAvailableActionsInput,
  ): Promise<ListAvailableActionsOutput>

  /**
   * Subscribe to action status events.
   *
   * @param {SubscribeToActionsInput} input Parameters used to subscribe to action
   *  status events.
   */
  subscribe(input: SubscribeToActionsInput): Promise<void>

  /**
   * Unsubscribe from action status events.
   *
   * @param {string} subscriptionId The unique identifier of the subscription to unsubscribe from.
   */
  unsubscribe(subscriptionId: string): void
}
