/**
 * Copyright © 2026 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { Pagination } from './common'

/**
 * Properties required to list analysis results.
 *
 * @interface ListAnalysisResultsInput
 * @property {string} virtualPresenceId The identifier of the virtual presence to list analysis results for.
 * @property {number} limit Number of items to return.
 * @property {string} nextToken A token generated by a previous call.
 */
export interface ListAnalysisResultsInput extends Pagination {
  virtualPresenceId: string
}
