/**
 * Copyright © 2026 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Pagination interface designed to be extended for list interfaces.
 *
 * @interface Pagination
 * @property {number} limit Number of items to return.  Will be defaulted if omitted.
 * @property {string} nextToken A token generated by a previous call.
 */
export interface Pagination {
  limit?: number
  nextToken?: string
}
