/**
 * Copyright © 2026 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { Pagination } from './common'

/**
 * Properties required to list data holders.
 *
 * @interface ListDataHoldersInput
 * @property {string} virtualPresenceId The identifier of the virtual presence to list data holders for.
 * @property {number} limit Number of items to return.
 * @property {string} nextToken A token generated by a previous call.
 */
export interface ListDataHoldersInput extends Pagination {
  virtualPresenceId: string
}

/**
 * Properties required to list scan summaries for a data holder.
 *
 * @interface ListDataHolderScanSummariesInput
 * @property {string} dataHolderId The identifier of the data holder to list scan summaries for.
 * @property {number} limit Number of items to return.
 * @property {string} nextToken A token generated by a previous call.
 */
export interface ListDataHolderScanSummariesInput extends Pagination {
  dataHolderId: string
}

/**
 * Options to control what `getDataHolder` returns.
 *
 * @interface GetDataHolderOptions
 * @property {boolean} includeScanSummary Whether to also fetch and attach the most recent
 *  scan summary to the returned data holder. Defaults to `true`. When `true`, the data holder
 *  and its latest scan summary are fetched concurrently.
 */
export interface GetDataHolderOptions {
  includeScanSummary?: boolean
}
