/**
 * Copyright © 2026 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { Pagination } from './common'

/**
 * Properties required to list data holders.
 *
 * @interface ListDataHoldersInput
 * @property {string} virtualPresenceId The identifier of the virtual presence to list data holders for.
 * @property {number} limit Number of items to return.
 * @property {string} nextToken A token generated by a previous call.
 */
export interface ListDataHoldersInput extends Pagination {
  virtualPresenceId: string
}
