/**
 * Copyright © 2026 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { Pagination } from './common'

/**
 * Properties required to connect a virtual presence with an auth code.
 *
 * @interface ConnectVirtualPresenceWithAuthCodeInput
 * @property {string} authCode An authorization code obtained from the OAuth flow.
 * @property {string} redirectUri The redirect URI that was used to obtain the
 *  authorization code.
 * @property {RelationshipProvider} relationshipProvider The relationship provider
 *  to associate with the connection.
 */
export interface ConnectVirtualPresenceWithAuthCodeInput {
  authCode: string
  redirectUri?: string
  relationshipProvider?: RelationshipProvider
}

/**
 * Properties required to connect a virtual presence with a refresh token.
 *
 * @interface ConnectVirtualPresenceWithRefreshTokenInput
 * @property {string} refreshToken The refresh token value.
 * @property {string} providerIdentity The identity associated with the provider.
 * @property {string[]} scopes Optional OAuth scopes associated with the token.
 * @property {number} expiresInEpochMs Optional expiration time in milliseconds since epoch.
 * @property {RelationshipProvider} relationshipProvider The relationship provider
 *  to associate with the connection.
 */
export interface ConnectVirtualPresenceWithRefreshTokenInput {
  refreshToken: string
  providerIdentity: string
  scopes?: string[]
  expiresInEpochMs?: number
  relationshipProvider?: RelationshipProvider
}

/**
 * Enumeration of the relationship providers that back a virtual presence connection.
 *
 * @property GMAIL_PROVIDER The Gmail relationship provider.
 * @property TEST_PROVIDER The test relationship provider.
 *
 * @enum
 */
export enum RelationshipProvider {
  GmailProvider = 'GMAIL_PROVIDER',
  TestProvider = 'TEST_PROVIDER',
}

/**
 * Properties required to list virtual presences for this client.
 *
 * @interface ListVirtualPresencesInput
 * @property {number} limit Number of items to return.
 * @property {string} nextToken A token generated by a previous call.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface ListVirtualPresencesInput extends Pagination {}

/**
 * Properties required to rescan a virtual presence.
 *
 * @interface RescanVirtualPresenceInput
 * @property {string} id The unique identifier of the virtual presence to rescan.
 * @property {ScanOptions} options Optional scan options to control the rescan behavior.
 */
export interface RescanVirtualPresenceInput {
  id: string
  options?: ScanOptions
}

/**
 * Options to control a rescan operation.
 *
 * @interface ScanOptions
 * @property {number} maximumItemsProcessed Maximum number of items to process during the scan.
 * @property {string} earliestScanDate Earliest date boundary for the scan (ISO 8601 string).
 * @property {string} latestScanDate Latest date boundary for the scan (ISO 8601 string).
 * @property {string[]} excludeDomains Domains to exclude from the scan.
 * @property {string[]} excludeCategories Categories to exclude from the scan.
 */
export interface ScanOptions {
  maximumItemsProcessed?: number
  earliestScanDate?: string
  latestScanDate?: string
  excludeDomains?: string[]
  excludeCategories?: string[]
}
